export const START_EXPRS = [
    ["abscess", "absceso"],
    ["ache", "dolor"],
    ["age", "edad"],
    ["allergy", "alergia"],
    ["aneurysm", "aneurisma"],
    ["ankle", "tobillo"],
    ["anxiety", "ansiedad"],
    ["arm", "brazo"],
    ["arrhythmia", "arritmia"],
    ["arthritis", "artritis"],
    ["asthma", "asma"],
    ["belch", "eructar"],
    ["bladder", "vejiga"],
    ["blind", "ciego"],
    ["blink", "parpadear"],
    ["blister", "ampolla"],
    ["blood", "sangre"],
    ["blood type", "grupo sanguíneo"],
    ["bone", "hueso"],
    ["brain", "cerebro"],
    ["breast", "seno"],
    ["breastfeed", "amamantar"],
    ["breathe", "respirar"],
    ["bronchitis", "bronquitis"],
    ["bruise", "cardenal"],
    ["calcium", "calcio"],
    ["calories", "calorías"],
    ["cancer", "cáncer"],
    ["chest", "pecho"],
    ["chickenpox", "varicela"],
    ["childbirth", "parto"],
    ["circulation", "circulación sanguínea"],
    ["clinic", "clínica"],
    ["cross-eyed", "bizco"],
    ["cry", "llorar"],
    ["doctor", "médico"],
    ["hair", "pelo"],
    ["heart", "corazón"],
    ["pimple", "espinilla"],
    ["stomach", "estómago"],
]

export const INITIAL_UIDDE = [
    "eng-000",
    "spa-000",
    // "fra-000",
]

export const INITIAL_UIDAL = [
    "tir-000",
    "arb-000",
    "mya-000",
    "pes-000",
    "yua-000",
]

export const UID_NAMES = {
    "eng-000": "English",
    "spa-000": "Spanish",
    "tir-000": "Tigrinya",
    "arb-000": "Arabic",
    "mya-000": "Burmese",
    "pes-000": "Farsi",
    "ell-000": "Greek",
    "prs-000": "Dari",
    "fra-000": "French",
    "pbu-000": "Pashto",
    "yua-000": "Yucatec Maya",
}