let notoEAFontNames = {
	// "Adlm": "Noto Sans Adlam",
	// "Aghb": "Noto Sans Caucasian Albanian",
	// "Ahom": "Noto Sans Ahom",
	"Arab": "Noto Naskh Arabic",
	"Armi": "Noto Sans Imperial Aramaic",
	"Armn": "Noto Sans Armenian",
	"Avst": "Noto Sans Avestan",
	"Bali": "Noto Sans Balinese",
	"Bamu": "Noto Sans Bamum",
	// "Bass": "Noto Sans Bassa Vah",
	"Batk": "Noto Sans Batak",
	"Beng": "Noto Sans Bengali",
	// "Bhks": "Noto Sans Bhaiksuki",
	// "Bopo": "Noto Sans TC",
	"Brah": "Noto Sans Brahmi",
	// "Brai": "Noto Sans Braille",
	"Bugi": "Noto Sans Buginese",
	"Buhd": "Noto Sans Buhid",
	// "Cakm": "Noto Sans Chakma",
	"Cans": "Noto Sans Canadian Aboriginal",
	"Cari": "Noto Sans Carian",
	"Cham": "Noto Sans Cham",
	"Cher": "Noto Sans Cherokee",
	"Copt": "Noto Sans Coptic",
	"Cprt": "Noto Sans Cypriot",
	"Deva": "Noto Sans Devanagari",
	"Dsrt": "Noto Sans Deseret",
	// "Dupl": "Noto Sans Duployan",
	"Egyp": "Noto Sans Egyptian Hieroglyphs",
	// "Elba": "Noto Sans Elbasan",
	"Ethi": "Noto Sans Ethiopic",
	"Geor": "Noto Sans Georgian",
	// "Glag": "Noto Sans Glagolitic",
	"Goth": "Noto Sans Gothic",
	// "Gran": "Noto Sans Grantha",
	"Gujr": "Noto Sans Gujarati",
	"Guru": "Noto Sans Gurmukhi",
	// "Hang": "Noto Sans KR",
	// "Hani": "Noto Sans TC",
	"Hano": "Noto Sans Hanunoo",
	// "Hatr": "Noto Sans Hatran",
	"Hebr": "Noto Sans Hebrew",
	// "Hira": "Noto Sans JP",
	// "Hluw": "Noto Sans Anatolian Hieroglyphs",
	// "Hmng": "Noto Sans Pahawh Hmong",
	// "Hrkt": "Noto Sans JP",
	// "Hung": "Noto Sans Old Hungarian",
	"Ital": "Noto Sans Old Italic",
	"Java": "Noto Sans Javanese",
	"Kali": "Noto Sans Kayah Li",
	// "Kana": "Noto Sans JP",
	"Khar": "Noto Sans Kharoshthi",
	"Khmr": "Noto Sans Khmer",
	// "Khoj": "Noto Sans Khojki",
	"Knda": "Noto Sans Kannada",
	"Kthi": "Noto Sans Kaithi",
	"Lana": "Noto Sans Tai Tham",
	"Laoo": "Noto Sans Lao",
	"Lepc": "Noto Sans Lepcha",
	"Limb": "Noto Sans Limbu",
	// "Lina": "Noto Sans Linear A",
	"Linb": "Noto Sans Linear B",
	"Lisu": "Noto Sans Lisu",
	"Lyci": "Noto Sans Lycian",
	"Lydi": "Noto Sans Lydian",
	// "Mahj": "Noto Sans Mahajani",
	"Mand": "Noto Sans Mandaic",
	// "Mani": "Noto Sans Manichaean",
	// "Marc": "Noto Sans Marchen",
	// "Mend": "Noto Sans Mende Kikakui",
	// "Merc": "Noto Sans Meroitic Cursive",
	// "Mero": "Noto Sans Meroitic Hieroglyphs",
	"Mlym": "Noto Sans Malayalam",
	// "Modi": "Noto Sans Modi",
	"Mong": "Noto Sans Mongolian",
	// "Mroo": "Noto Sans Mro",
	"Mtei": "Noto Sans Meetei Mayek",
	// "Mult": "Noto Sans Multani",
	"Mymr": "Noto Sans Myanmar",
	// "Narb": "Noto Sans Old North Arabian",
	// "Nbat": "Noto Sans Nabataean",
	// "Newa": "Noto Sans Newa",
	// "Nkoo": "Noto Sans N'Ko",
	"Ogam": "Noto Sans Ogham",
	"Olck": "Noto Sans Ol Chiki",
	"Orkh": "Noto Sans Old Turkic",
	"Orya": "Noto Sans Oriya",
	// "Osge": "Noto Sans Osage",
	"Osma": "Noto Sans Osmanya",
	// "Palm": "Noto Sans Palmyrene",
	// "Pauc": "Noto Sans Pau Cin Hau",
	// "Perm": "Noto Sans Old Permic",
	"Phag": "Noto Sans Phags Pa",
	"Phli": "Noto Sans Inscriptional Pahlavi",
	// "Phlp": "Noto Sans Psalter Pahlavi",
	"Phnx": "Noto Sans Phoenician",
	// "Plrd": "Noto Sans Miao",
	"Prti": "Noto Sans Inscriptional Parthian",
	"Rjng": "Noto Sans Rejang",
	"Runr": "Noto Sans Runic",
	"Samr": "Noto Sans Samaritan",
	"Sarb": "Noto Sans Old South Arabian",
	"Saur": "Noto Sans Saurashtra",
	// "Sgnw": "Noto Sans SignWriting",
	"Shaw": "Noto Sans Shavian",
	// "Shrd": "Noto Sans Sharada",
	// "Sidd": "Noto Sans Siddham",
	// "Sind": "Noto Sans Khudawadi",
	"Sinh": "Noto Sans Sinhala",
	// "Sora": "Noto Sans Sora Sompeng",
	"Sund": "Noto Sans Sundanese",
	"Sylo": "Noto Sans Syloti Nagri",
	"Syrc": "Noto Sans Syriac Estrangela",
	"Syre": "Noto Sans Syriac Estrangela",
	"Syrj": "Noto Sans Syriac Western",
	"Syrn": "Noto Sans Syriac Eastern",
    "Tagb": "Noto Sans Tagbanwa",
	// "Takr": "Noto Sans Takri",
	"Tale": "Noto Sans Tai Le",
	"Talu": "Noto Sans New Tai Lue",
	"Taml": "Noto Sans Tamil",
	// "Tang": "Noto Sans Tangut",
	"Tavt": "Noto Sans Tai Viet",
	"Telu": "Noto Sans Telugu",
	"Tfng": "Noto Sans Tifinagh",
	"Tglg": "Noto Sans Tagalog",
	"Thaa": "Noto Sans Thaana",
	"Thai": "Noto Sans Thai",
	"Tibt": "Noto Sans Tibetan",
	// "Tirh": "Noto Sans Tirhuta",
	"Ugar": "Noto Sans Ugaritic",
	"Vaii": "Noto Sans Vai",
	// "Wara": "Noto Sans Warang Citi",
	"Xpeo": "Noto Sans Old Persian",
	"Xsux": "Noto Sans Cuneiform",
	"Yiii": "Noto Sans Yi",
};

let otherFonts = {
    "Latn": ["Noto Sans", "https://fonts.googleapis.com/css?family=Noto+Sans"],
    "Cyrl": ["Noto Sans", "https://fonts.googleapis.com/css?family=Noto+Sans"],
    "Grek": ["Noto Sans", "https://fonts.googleapis.com/css?family=Noto+Sans"],
    "Zinh": ["Noto Sans", "https://fonts.googleapis.com/css?family=Noto+Sans"],
    "Zxxx": ["Noto Sans", "https://fonts.googleapis.com/css?family=Noto+Sans"],
    "Zyyy": ["Noto Sans", "https://fonts.googleapis.com/css?family=Noto+Sans"],
}

let notoEAFontUrls = Object.entries(notoEAFontNames).reduce((o, [code, name]) => {
    let fileName = name.toLowerCase().replace(/\s/g, "");
    o[code] = `https://fonts.googleapis.com/earlyaccess/${fileName}.css`;
    return(o);
}, {})

let otherFontNames = {};
let otherFontUrls = {};
Object.entries(otherFonts).forEach(([code, [name, url]]) => {
    otherFontNames[code] = name;
    otherFontUrls[code] = url;
});

export const FONT_NAMES = {
    ...notoEAFontNames,
    ...otherFontNames,
};

export const FONT_URLS = {
    ...notoEAFontUrls,
    ...otherFontUrls,
}